version: "3.2"
services: 
    db:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
        ports:
            - 3306:3306
        container_name: db

    api:
        build: .
        ports: 
            - 5000:5000
        depends_on: 
            - db
        container_name: api